# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebateSide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(max_length=250)),
                ('side_points', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DebateTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.CharField(max_length=500)),
                ('good_point', models.BigIntegerField()),
                ('bad_point', models.BigIntegerField()),
                ('debate_side', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.DebateSide')),
            ],
        ),
        migrations.AddField(
            model_name='debateside',
            name='debate_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='debate.DebateTopic'),
        ),
    ]
