# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatetopic',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
