# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20170808_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
