# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 03:54
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0004_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_topics',
            field=multiselectfield.db.fields.MultiSelectField(default=('Odd News', 'Odd News'), max_length=200, verbose_name=(('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Odd News', 'Odd News'), ('Local', 'Local'), ('International', 'International'))),
        ),
    ]
