# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 03:55
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0005_userprofile_favorite_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Odd News', 'Odd News'), ('Local', 'Local'), ('International', 'International')], default=('Odd News', 'Odd News'), max_length=66),
        ),
    ]
