# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0006_auto_20170807_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_topics',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sports', 'Sports'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Fashion', 'Fashion'), ('Odd News', 'Odd News'), ('Local', 'Local'), ('International', 'International'), ('Music', 'Music'), ('Trending', 'Trending'), ('Technology', 'Technology'), ('Science', 'Science'), ('Business', 'Business'), ('Finance', 'Finance'), ('Television', 'Television'), ('Movies', 'Movies'), ('Celebrities', 'Celebrities'), ('Social Media', 'Social Media'), ('Food', 'Food'), ('Health', 'Health'), ('Nature', 'Nature'), ('Kids', 'Kids'), ('Breaking News', 'Breaking News'), ('Travel', 'Travel'), ('Substances', 'Substances'), ('United States', 'United States'), ('Andimals', 'Animals'), ('Art', 'Art'), ('Education', 'Education'), ('Employment', 'Employment'), ('Brands', 'Brands')], default=('Odd News', 'Odd News'), max_length=271),
        ),
    ]
