# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0014_debatetopic_topics_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debatetopic',
            old_name='topics_tags',
            new_name='topic_tags',
        ),
    ]
