# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0015_auto_20170821_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatetopic',
            name='article_URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='debatetopic',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
