# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0017_auto_20170824_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='debate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.DebateTopic'),
        ),
    ]
