# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0019_auto_20170825_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='debate_side',
        ),
    ]
