# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0022_auto_20170828_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatetopic',
            name='article_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
