# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0024_auto_20170828_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatetopic',
            name='topic',
            field=models.CharField(default='', max_length=250),
        ),
    ]
