# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0025_auto_20170901_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debatetopic',
            name='topic',
            field=models.CharField(max_length=250),
        ),
    ]
